
name: CI
env:
  directory: ./project
on:
   # События, которые запускают jobs
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

# jobs запускаются параллельно, если не указана последовательность
jobs:
    # Название job вы можете назвать как угодно
    my_build_job:
      # Операционная система в виртуальной машине, в которой запускаются процессы
      runs-on: ubuntu-latest
        # Шаги
      steps:
          # Actions от github: проверяет репозиторий, гит и т.д.
          - uses: actions/checkout@v4
            with:
              sparse-checkout: |
                file
              sparse-checkout-cone-mode: false
        
          - name: check file
            run: ls -l 

          # Пример однолинейного простого скрипта shell
          - name: Run a one-line script
            run: echo Hello, world!

          # Пример многолинейного скрипта shell
          - name: Run a multi-line script
            run: |
                echo Add other actions to build,
                echo test, and deploy your project.


    my_test_job:
      needs: [my_build_job]
      runs-on: ubuntu-latest
      steps:
          - name: doing smth
            run: uptime

          - name: a few jobs
            run: | 
                  mkdir ${{env.directory}}
                  cd ${{env.directory}}
                  pwd
                  
            
